//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_FIlteringData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
    
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
