//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_FIlteringData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SalesRecordId { get; set; }
        public int AgentId { get; set; }
        public int TerritoryId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Product Product { get; set; }
        public virtual Territory Territory { get; set; }
    }
}
